// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: model_server.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ModelServer_ModelCall_FullMethodName = "/modelserver.ModelServer/ModelCall"
)

// ModelServerClient is the client API for ModelServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelServerClient interface {
	ModelCall(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error)
}

type modelServerClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServerClient(cc grpc.ClientConnInterface) ModelServerClient {
	return &modelServerClient{cc}
}

func (c *modelServerClient) ModelCall(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, ModelServer_ModelCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServerServer is the server API for ModelServer service.
// All implementations must embed UnimplementedModelServerServer
// for forward compatibility
type ModelServerServer interface {
	ModelCall(context.Context, *ModelRequest) (*ModelResponse, error)
	mustEmbedUnimplementedModelServerServer()
}

// UnimplementedModelServerServer must be embedded to have forward compatible implementations.
type UnimplementedModelServerServer struct {
}

func (UnimplementedModelServerServer) ModelCall(context.Context, *ModelRequest) (*ModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelCall not implemented")
}
func (UnimplementedModelServerServer) mustEmbedUnimplementedModelServerServer() {}

// UnsafeModelServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServerServer will
// result in compilation errors.
type UnsafeModelServerServer interface {
	mustEmbedUnimplementedModelServerServer()
}

func RegisterModelServerServer(s grpc.ServiceRegistrar, srv ModelServerServer) {
	s.RegisterService(&ModelServer_ServiceDesc, srv)
}

func _ModelServer_ModelCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServerServer).ModelCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelServer_ModelCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServerServer).ModelCall(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelServer_ServiceDesc is the grpc.ServiceDesc for ModelServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modelserver.ModelServer",
	HandlerType: (*ModelServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModelCall",
			Handler:    _ModelServer_ModelCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model_server.proto",
}
